// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-dark-factory-watcher/pkg"
	"github.com/bborbe/time"
)

type GitHubClient struct {
	GetContentStub        func(context.Context, string, string, string, string) ([]byte, error)
	getContentMutex       sync.RWMutex
	getContentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	getContentReturns struct {
		result1 []byte
		result2 error
	}
	getContentReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	GetPRDetailsStub        func(context.Context, string, string, int) (pkg.PRDetails, error)
	getPRDetailsMutex       sync.RWMutex
	getPRDetailsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	getPRDetailsReturns struct {
		result1 pkg.PRDetails
		result2 error
	}
	getPRDetailsReturnsOnCall map[int]struct {
		result1 pkg.PRDetails
		result2 error
	}
	IsNotFoundStub        func(error) bool
	isNotFoundMutex       sync.RWMutex
	isNotFoundArgsForCall []struct {
		arg1 error
	}
	isNotFoundReturns struct {
		result1 bool
	}
	isNotFoundReturnsOnCall map[int]struct {
		result1 bool
	}
	ListDirStub        func(context.Context, string, string, string, string) ([]string, error)
	listDirMutex       sync.RWMutex
	listDirArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	listDirReturns struct {
		result1 []string
		result2 error
	}
	listDirReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ListPRFilesStub        func(context.Context, string, string, int) ([]string, error)
	listPRFilesMutex       sync.RWMutex
	listPRFilesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	listPRFilesReturns struct {
		result1 []string
		result2 error
	}
	listPRFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	SearchPRsStub        func(context.Context, string, time.DateTime, int) (pkg.SearchResult, error)
	searchPRsMutex       sync.RWMutex
	searchPRsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.DateTime
		arg4 int
	}
	searchPRsReturns struct {
		result1 pkg.SearchResult
		result2 error
	}
	searchPRsReturnsOnCall map[int]struct {
		result1 pkg.SearchResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) GetContent(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) ([]byte, error) {
	fake.getContentMutex.Lock()
	ret, specificReturn := fake.getContentReturnsOnCall[len(fake.getContentArgsForCall)]
	fake.getContentArgsForCall = append(fake.getContentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.GetContentStub
	fakeReturns := fake.getContentReturns
	fake.recordInvocation("GetContent", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.getContentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetContentCallCount() int {
	fake.getContentMutex.RLock()
	defer fake.getContentMutex.RUnlock()
	return len(fake.getContentArgsForCall)
}

func (fake *GitHubClient) GetContentCalls(stub func(context.Context, string, string, string, string) ([]byte, error)) {
	fake.getContentMutex.Lock()
	defer fake.getContentMutex.Unlock()
	fake.GetContentStub = stub
}

func (fake *GitHubClient) GetContentArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.getContentMutex.RLock()
	defer fake.getContentMutex.RUnlock()
	argsForCall := fake.getContentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *GitHubClient) GetContentReturns(result1 []byte, result2 error) {
	fake.getContentMutex.Lock()
	defer fake.getContentMutex.Unlock()
	fake.GetContentStub = nil
	fake.getContentReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetContentReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getContentMutex.Lock()
	defer fake.getContentMutex.Unlock()
	fake.GetContentStub = nil
	if fake.getContentReturnsOnCall == nil {
		fake.getContentReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getContentReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPRDetails(arg1 context.Context, arg2 string, arg3 string, arg4 int) (pkg.PRDetails, error) {
	fake.getPRDetailsMutex.Lock()
	ret, specificReturn := fake.getPRDetailsReturnsOnCall[len(fake.getPRDetailsArgsForCall)]
	fake.getPRDetailsArgsForCall = append(fake.getPRDetailsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetPRDetailsStub
	fakeReturns := fake.getPRDetailsReturns
	fake.recordInvocation("GetPRDetails", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPRDetailsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetPRDetailsCallCount() int {
	fake.getPRDetailsMutex.RLock()
	defer fake.getPRDetailsMutex.RUnlock()
	return len(fake.getPRDetailsArgsForCall)
}

func (fake *GitHubClient) GetPRDetailsCalls(stub func(context.Context, string, string, int) (pkg.PRDetails, error)) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = stub
}

func (fake *GitHubClient) GetPRDetailsArgsForCall(i int) (context.Context, string, string, int) {
	fake.getPRDetailsMutex.RLock()
	defer fake.getPRDetailsMutex.RUnlock()
	argsForCall := fake.getPRDetailsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) GetPRDetailsReturns(result1 pkg.PRDetails, result2 error) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = nil
	fake.getPRDetailsReturns = struct {
		result1 pkg.PRDetails
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPRDetailsReturnsOnCall(i int, result1 pkg.PRDetails, result2 error) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = nil
	if fake.getPRDetailsReturnsOnCall == nil {
		fake.getPRDetailsReturnsOnCall = make(map[int]struct {
			result1 pkg.PRDetails
			result2 error
		})
	}
	fake.getPRDetailsReturnsOnCall[i] = struct {
		result1 pkg.PRDetails
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) IsNotFound(arg1 error) bool {
	fake.isNotFoundMutex.Lock()
	ret, specificReturn := fake.isNotFoundReturnsOnCall[len(fake.isNotFoundArgsForCall)]
	fake.isNotFoundArgsForCall = append(fake.isNotFoundArgsForCall, struct {
		arg1 error
	}{arg1})
	stub := fake.IsNotFoundStub
	fakeReturns := fake.isNotFoundReturns
	fake.recordInvocation("IsNotFound", []interface{}{arg1})
	fake.isNotFoundMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitHubClient) IsNotFoundCallCount() int {
	fake.isNotFoundMutex.RLock()
	defer fake.isNotFoundMutex.RUnlock()
	return len(fake.isNotFoundArgsForCall)
}

func (fake *GitHubClient) IsNotFoundCalls(stub func(error) bool) {
	fake.isNotFoundMutex.Lock()
	defer fake.isNotFoundMutex.Unlock()
	fake.IsNotFoundStub = stub
}

func (fake *GitHubClient) IsNotFoundArgsForCall(i int) error {
	fake.isNotFoundMutex.RLock()
	defer fake.isNotFoundMutex.RUnlock()
	argsForCall := fake.isNotFoundArgsForCall[i]
	return argsForCall.arg1
}

func (fake *GitHubClient) IsNotFoundReturns(result1 bool) {
	fake.isNotFoundMutex.Lock()
	defer fake.isNotFoundMutex.Unlock()
	fake.IsNotFoundStub = nil
	fake.isNotFoundReturns = struct {
		result1 bool
	}{result1}
}

func (fake *GitHubClient) IsNotFoundReturnsOnCall(i int, result1 bool) {
	fake.isNotFoundMutex.Lock()
	defer fake.isNotFoundMutex.Unlock()
	fake.IsNotFoundStub = nil
	if fake.isNotFoundReturnsOnCall == nil {
		fake.isNotFoundReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isNotFoundReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *GitHubClient) ListDir(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) ([]string, error) {
	fake.listDirMutex.Lock()
	ret, specificReturn := fake.listDirReturnsOnCall[len(fake.listDirArgsForCall)]
	fake.listDirArgsForCall = append(fake.listDirArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListDirStub
	fakeReturns := fake.listDirReturns
	fake.recordInvocation("ListDir", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listDirMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) ListDirCallCount() int {
	fake.listDirMutex.RLock()
	defer fake.listDirMutex.RUnlock()
	return len(fake.listDirArgsForCall)
}

func (fake *GitHubClient) ListDirCalls(stub func(context.Context, string, string, string, string) ([]string, error)) {
	fake.listDirMutex.Lock()
	defer fake.listDirMutex.Unlock()
	fake.ListDirStub = stub
}

func (fake *GitHubClient) ListDirArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.listDirMutex.RLock()
	defer fake.listDirMutex.RUnlock()
	argsForCall := fake.listDirArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *GitHubClient) ListDirReturns(result1 []string, result2 error) {
	fake.listDirMutex.Lock()
	defer fake.listDirMutex.Unlock()
	fake.ListDirStub = nil
	fake.listDirReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListDirReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listDirMutex.Lock()
	defer fake.listDirMutex.Unlock()
	fake.ListDirStub = nil
	if fake.listDirReturnsOnCall == nil {
		fake.listDirReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listDirReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListPRFiles(arg1 context.Context, arg2 string, arg3 string, arg4 int) ([]string, error) {
	fake.listPRFilesMutex.Lock()
	ret, specificReturn := fake.listPRFilesReturnsOnCall[len(fake.listPRFilesArgsForCall)]
	fake.listPRFilesArgsForCall = append(fake.listPRFilesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListPRFilesStub
	fakeReturns := fake.listPRFilesReturns
	fake.recordInvocation("ListPRFiles", []interface{}{arg1, arg2, arg3, arg4})
	fake.listPRFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) ListPRFilesCallCount() int {
	fake.listPRFilesMutex.RLock()
	defer fake.listPRFilesMutex.RUnlock()
	return len(fake.listPRFilesArgsForCall)
}

func (fake *GitHubClient) ListPRFilesCalls(stub func(context.Context, string, string, int) ([]string, error)) {
	fake.listPRFilesMutex.Lock()
	defer fake.listPRFilesMutex.Unlock()
	fake.ListPRFilesStub = stub
}

func (fake *GitHubClient) ListPRFilesArgsForCall(i int) (context.Context, string, string, int) {
	fake.listPRFilesMutex.RLock()
	defer fake.listPRFilesMutex.RUnlock()
	argsForCall := fake.listPRFilesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) ListPRFilesReturns(result1 []string, result2 error) {
	fake.listPRFilesMutex.Lock()
	defer fake.listPRFilesMutex.Unlock()
	fake.ListPRFilesStub = nil
	fake.listPRFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListPRFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listPRFilesMutex.Lock()
	defer fake.listPRFilesMutex.Unlock()
	fake.ListPRFilesStub = nil
	if fake.listPRFilesReturnsOnCall == nil {
		fake.listPRFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listPRFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) SearchPRs(arg1 context.Context, arg2 string, arg3 time.DateTime, arg4 int) (pkg.SearchResult, error) {
	fake.searchPRsMutex.Lock()
	ret, specificReturn := fake.searchPRsReturnsOnCall[len(fake.searchPRsArgsForCall)]
	fake.searchPRsArgsForCall = append(fake.searchPRsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.DateTime
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.SearchPRsStub
	fakeReturns := fake.searchPRsReturns
	fake.recordInvocation("SearchPRs", []interface{}{arg1, arg2, arg3, arg4})
	fake.searchPRsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) SearchPRsCallCount() int {
	fake.searchPRsMutex.RLock()
	defer fake.searchPRsMutex.RUnlock()
	return len(fake.searchPRsArgsForCall)
}

func (fake *GitHubClient) SearchPRsCalls(stub func(context.Context, string, time.DateTime, int) (pkg.SearchResult, error)) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = stub
}

func (fake *GitHubClient) SearchPRsArgsForCall(i int) (context.Context, string, time.DateTime, int) {
	fake.searchPRsMutex.RLock()
	defer fake.searchPRsMutex.RUnlock()
	argsForCall := fake.searchPRsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) SearchPRsReturns(result1 pkg.SearchResult, result2 error) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = nil
	fake.searchPRsReturns = struct {
		result1 pkg.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) SearchPRsReturnsOnCall(i int, result1 pkg.SearchResult, result2 error) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = nil
	if fake.searchPRsReturnsOnCall == nil {
		fake.searchPRsReturnsOnCall = make(map[int]struct {
			result1 pkg.SearchResult
			result2 error
		})
	}
	fake.searchPRsReturnsOnCall[i] = struct {
		result1 pkg.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GitHubClient = new(GitHubClient)
